#!/bin/bash
#
# cf-push
#
# This is a Cisco Cloud Center external service example to deploy an Cloud Foundry Application
# Cloud Foundry is a PaaS system, so what we are doing is front ending the Login and Push
# Process with a Cloud Center button that will ask for all the needed information to deploy
# an application into the Cloud Foundry PaaS platform.  
# 
# This service leverages the default Cloud Foundry CLI commands as well as the default ENV vars that CF uses
# for login, password, Organization, Space, API endpoint.  I have defined them below. 
# 
#
# Cloud Foundry env vars to be used or mapped into Cloud Center
#
#		$CF_API - API endpoint of cloud foundry instance  
#		$CF_USER - User name in cloud foundry
#		$CF_PASS - Password
#		$CF_ORG - Org
#		$CF_SPACE - Space
#		$CF_APP_URL - URL to HTTP location to grab application
#		$CF_APP_NAME - App name in CF that we are creating 
#		$APP_DIR - Name of the directory the applications is in
# 		$APP_BUILD_TYPE - type of application to compile, mavin, gradle, python, static
#		(today we only have gradle in this example, enhancement to expand it to the UI)
#
# Locally we will use a few also
# 
#		cmd for our case statement is the first parameter passed in is either start or stop
# 		to run: service <start> or <stop> 
#

exec > >(tee -a /var/tmp/swarm-init_$$.log) 2>&1

source /usr/local/osmosix/etc/.osmosix.sh
source /usr/local/osmosix/etc/userenv
source /usr/local/osmosix/service/utils/cfgutil.sh
source /usr/local/osmosix/service/utils/agent_util.sh

cd ~

# Move over cliqr repo and move back at end.
sudo mv /etc/yum.repos.d/cliqr.repo ~

agentSendLogMessage "EXTERNAL SERVICE - Cloud Foundry Service to push an application has started"
agentSendLogMessage "We need to update the OS and add some packages to run the service first"
agentSendLogMessage "Executing a YUM UPDATE on BASE OS to insure its clean" 

sudo yum update -y

# sudo yum install -y epel-release

. /utils.sh


env

agentSendLogMessage $(env)

# cmd is our case variable for START and STOP of this Cloud Foundry service
cmd=$1
serviceStatus=""

if [ -n "$gitTag" ]; then
    agentSendLogMessage  "Found gitTag parameter gitTag = ${gitTag}"
else
     agentSendLogMessage  "Didn't find custom parameter gitTag. Using gitTag=master"
     gitTag="Cloud Foundry push service for Cisco Cloud Center"
fi



# Install wget to use as a vehicle to move bits around
agentSendLogMessage "INSTALL - Installing wget for application bits download"
sudo yum install -y wget

# Fetch the bits for the CLI using WGET
agentSendLogMessage "Downloading the CLI tools needed for cloud foundry"
sudo wget -O /etc/yum.repos.d/cloudfoundry-cli.repo https://packages.cloudfoundry.org/fedora/cloudfoundry-cli.repo

# Install Cloud Foundry CLI called CF
agentSendLogMessage "INSTALL - Installing Cloud Foundry CLI client ..."
sudo yum install -y cf-cli

# Install GIT to fetch applications bits with
agentSendLogMessage "INSTALL - git to use to get applications bits into this service to deploy" 
sudo yum install -y git

agentSendLogMessage "All done with needed packages for the service, now to login, compile and push app"

# Run the Cloud Foundry Push Service
case $cmd in
        start)
    	  agentSendLogMessage "Executing START in the Script to login, GIT, Compile and CF Push App" 
      	  # Here is our Name of the App in CF   
          agentSendLogMessage "Cloud Foundry Application name to deploy is  $CF_APP_NAME"
          # Next clone the app package from github     
          agentSendLogMessage "DOWNLOADING - GIT CLONE downloading ... the Application from $CF_APP_URL and saving locally"
          git clone $CF_APP_URL
          APP_DIR=$(echo $CF_APP_URL | sed 's/.*\///')
          agentSendLogMessage "INFORMATIONAL - Changing directory to $APP_DIR where the application is stored"
          cd $APP_DIR
          pwd > wd.log
          WD_LOG=$(cat wd.log)
          agentSendLogMessage "INFORMATIONAL - Working directory for App is $WD_LOG"
          # Choose Application environment or build type
          case $APP_BUILD_TYPE in
          	Gradle)
          		agentSendLogMessage "GRADLE APPLICATION - Need to install JAVA compiler first"
          		agentSendLogMessage "INSTALLING - Java8 for gradle JAVA compiles"
				sudo yum install -y java-1.8.0-openjdk-headless
				sudo yum install -y java-1.8.0-openjdk-devel
          		agentSendLogMessage "COMPILING - The application with gradle, this could take a long time ...."
          		# chmod +x gradlew 
                /root/$APP_DIR/gradlew clean assemble > compile.log
                COMPILE_LOG=$(tail compile.log)
                appSendLogMessage "$COMPILE_LOG"
           	 ;;
           	 Python)
           	 agentSendLogMessage "PYTHON APPLICATION - Processing Application in Cloud Foundry"
           	   # No compile necessary
           	 ;;
           	 Web)
           		agentSendLogMessage "WEBSITE APPLICATION - Processing Application in Cloud Foundry"
           	   # check for static file, for php and static web apps
           	 ;;
           	 PHP)
           	 	agentSendLogMessage "PHP APPLICATION - Processing Application in Cloud Foundry"
           	   # Nothing to do here, either php or html will be seen
           	 ;;          	   
          esac
          # This is the Meat of the service, call cf cli and cf push the application to CF
          agentSendLogMessage "AUTHENICATING - into Cloud Foundry using the following ...."
          agentSendLogMessage "cf login -a $CF_API -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE"
          cf login -a $CF_API -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE
          agentSendLogMessage "DEPLOYING APPLICATION - With cf push $CF_APP_NAME" 
          cf push $CF_APP_NAME > cfrun.log
          CF_LOG=$(cat cfrun.log)
          agentSendLogMessage "INFORMATIONAL - Lets look at the output from Cloud Foundry after the push" 
          agentSendLogMessage "$CF_LOG"
          agentSendLogMessage "Cloud Foundry Application now deployed"
          serviceStatus="Our internal Service has now been Started"
        ;;
        stop)
          # To stop the service, first log back into Cloud Foundry, then delete the app by name
          agentSendLogMessage "AUTHENICATING - into Cloud Foundry using the following ...."
          agentSendLogMessage "cf login -a $CF_API -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE"
          cf login -a $CF_API -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE   
          agentSendLogMessage "REMOVE - delete a application called $CF_APP_NAME"
          cf delete $CF_APP_NAME
          serviceStatus="Stopped"
        ;;
        *)
          serviceStatus="Error: Not a valid argument"
        exit 127
        ;;
esac
sudo mv ~/cliqr.repo /etc/yum.repos.d/
